import type { ConnectorRegistryRecord, SaveConnectorRegistryRecord } from "@lemmacomputer/workspace-store";

export type ConnectorDefinition = ConnectorRegistryRecord;

export type ConnectorActivationReadiness = "ready" | "setup_required" | "request_access";
export type ConnectorActivationAction = "connect" | "view_setup" | "view_requirements";

export type ConnectorActivation = {
  readiness: ConnectorActivationReadiness;
  action: ConnectorActivationAction;
  message: string;
};

// `withheld` keeps an entry in source without publishing it. A withheld
// connector is never seeded, listed, connectable, or granted gateway egress,
// but its name, branding, icon, and scopes survive so restoring it is a
// one-line change once the blocking condition is resolved.
type CatalogConnector = Omit<SaveConnectorRegistryRecord, "tenantId"> & { withheld?: string };

const remote = (connector: Omit<CatalogConnector, "policySupport" | "source" | "createdBy">): CatalogConnector => ({
  ...connector,
  policySupport: "automatic",
  source: "built-in",
  createdBy: "lemmacomputer",
});

// A provider that operates an allowlisted registration endpoint accepts only
// the OAuth clients it has approved by hostname, so no LemmaComputer
// installation can complete the flow. Withholding these is not a deployment
// gap; restoring one requires the provider to admit the deployment's callback
// origin or to issue static client credentials.
const REGISTRATION_ALLOWLISTED =
  "The provider restricts dynamic client registration to its own approved callback hosts";
// A provider that publishes no registration endpoint requires the operator to
// create an OAuth application in the provider's developer portal and supply
// static credentials, the way GitHub and Google Workspace already are wired in
// config/litellm/config.yaml. Withheld until those credentials exist.
const STATIC_CREDENTIALS_REQUIRED =
  "The provider publishes no registration endpoint and needs operator-supplied OAuth app credentials";

const readyActivation: ConnectorActivation = { readiness: "ready", action: "connect", message: "This approved service is ready to connect." };
// Catalog entries are approved remote MCP endpoints. Discovery and any
// provider-specific OAuth requirements are intentionally attempted only after
// the user selects Connect. A failed attempt remains disconnected, so no tools
// are projected into the workspace until authorization succeeds.
export const connectorActivation = (_connector: Pick<ConnectorDefinition, "id" | "source">): ConnectorActivation => ({
  ...readyActivation,
});

// These are provider-hosted remote MCP endpoints, not a tool allowlist. The
// Connections screen may display the full catalog without registering every
// server. Control registers one only after its owner selects Connect, and the
// runtime projection still requires that person's successful connection.
const remoteCatalog: CatalogConnector[] = [
  remote({
    id: "gmail",
    serverId: "lemmacomputer_gmail",
    serverName: "lemmacomputer_gmail",
    name: "Gmail",
    shortDescription: "Search mail and prepare follow-ups",
    description: "Use the Gmail messages, drafts, and mailbox context your Google Workspace account authorizes.",
    category: "Productivity",
    services: ["Mail", "Drafts", "Search"],
    endpointUrl: "https://gmailmcp.googleapis.com/mcp/v1",
    authorizationOrigins: ["https://accounts.google.com", "https://oauth2.googleapis.com"],
    scopes: [],
    brand: "gmail",
  }),
  remote({
    id: "google-drive",
    serverId: "lemmacomputer_google_drive",
    serverName: "lemmacomputer_google_drive",
    name: "Google Drive",
    shortDescription: "Find and work with shared files",
    description: "Use the Google Drive files and folders your Google Workspace account authorizes.",
    category: "Productivity",
    services: ["Files", "Folders", "Search"],
    endpointUrl: "https://drivemcp.googleapis.com/mcp/v1",
    authorizationOrigins: ["https://accounts.google.com", "https://oauth2.googleapis.com"],
    scopes: [],
    brand: "google-drive",
  }),
  remote({
    id: "google-calendar",
    serverId: "lemmacomputer_google_calendar",
    serverName: "lemmacomputer_google_calendar",
    name: "Google Calendar",
    shortDescription: "Review availability and manage events",
    description: "Use the Google Calendar events and availability your Google Workspace account authorizes.",
    category: "Productivity",
    services: ["Events", "Availability", "Scheduling"],
    endpointUrl: "https://calendarmcp.googleapis.com/mcp/v1",
    authorizationOrigins: ["https://accounts.google.com", "https://oauth2.googleapis.com"],
    scopes: [],
    brand: "google-calendar",
  }),
  remote({
    id: "notion",
    serverId: "lemmacomputer_notion",
    serverName: "lemmacomputer_notion",
    name: "Notion",
    shortDescription: "Search and update workspace knowledge",
    description: "Search and update the pages, databases, and knowledge your Notion account can access.",
    category: "Productivity",
    services: ["Pages", "Databases", "Search"],
    endpointUrl: "https://mcp.notion.com/mcp",
    authorizationOrigins: ["https://mcp.notion.com"],
    scopes: ["default"],
    brand: "notion",
  }),
  remote({
    id: "linear",
    serverId: "lemmacomputer_linear",
    serverName: "lemmacomputer_linear",
    name: "Linear",
    shortDescription: "Plan projects, issues, and product work",
    description: "Plan and follow product work across the issues, projects, and comments your account can access.",
    category: "Productivity",
    services: ["Issues", "Projects", "Comments"],
    endpointUrl: "https://mcp.linear.app/mcp",
    authorizationOrigins: ["https://mcp.linear.app"],
    scopes: ["read"],
    brand: "linear",
  }),
  remote({
    id: "atlassian",
    serverId: "lemmacomputer_atlassian",
    serverName: "lemmacomputer_atlassian",
    name: "Atlassian",
    shortDescription: "Work across Jira and Confluence",
    description: "Bring approved Jira work and Confluence knowledge into your workspace.",
    category: "Productivity",
    services: ["Jira", "Confluence", "Teamwork Graph"],
    endpointUrl: "https://mcp.atlassian.com/v1/mcp/authv2",
    authorizationOrigins: ["https://auth.atlassian.com"],
    scopes: [
      "read:me",
      "read:account",
      "offline_access",
      "email",
      "read:jira-work",
      "search:confluence",
      "read:confluence-user",
      "read:page:confluence",
      "read:comment:confluence",
      "read:space:confluence",
    ],
    brand: "atlassian",
  }),
  remote({
    id: "asana",
    withheld: STATIC_CREDENTIALS_REQUIRED,
    serverId: "lemmacomputer_asana",
    serverName: "lemmacomputer_asana",
    name: "Asana",
    shortDescription: "Manage tasks, projects, and reports",
    description: "Work with the tasks and projects your Asana account is authorized to access.",
    category: "Productivity",
    services: ["Tasks", "Projects", "Reports"],
    endpointUrl: "https://mcp.asana.com/v2/mcp",
    authorizationOrigins: ["https://mcp.asana.com", "https://app.asana.com"],
    scopes: [],
    brand: "asana",
  }),
  remote({
    id: "figma",
    withheld: REGISTRATION_ALLOWLISTED,
    serverId: "lemmacomputer_figma",
    serverName: "lemmacomputer_figma",
    name: "Figma",
    shortDescription: "Use design context from Figma files",
    description: "Retrieve the design context, variables, and components your Figma account can access.",
    category: "Productivity",
    services: ["Design context", "Components", "Variables"],
    endpointUrl: "https://mcp.figma.com/mcp",
    authorizationOrigins: ["https://mcp.figma.com", "https://www.figma.com"],
    scopes: [],
    brand: "figma",
  }),
  remote({
    id: "canva",
    serverId: "lemmacomputer_canva",
    serverName: "lemmacomputer_canva",
    name: "Canva",
    shortDescription: "Create and update designs with approved assets",
    description: "Create, edit, search, and export the Canva designs, assets, and brand content your account authorizes.",
    category: "Productivity",
    services: ["Designs", "Assets", "Brand kits"],
    endpointUrl: "https://mcp.canva.com/mcp",
    authorizationOrigins: ["https://mcp.canva.com"],
    scopes: [],
    brand: "canva",
  }),
  remote({
    id: "monday",
    serverId: "lemmacomputer_monday",
    serverName: "lemmacomputer_monday",
    name: "monday.com",
    shortDescription: "Manage boards, items, and workflows",
    description: "Use the monday.com boards, items, and workflows your account authorizes.",
    category: "Productivity",
    services: ["Boards", "Items", "Workflows"],
    endpointUrl: "https://mcp.monday.com/mcp",
    // Monday delegates authorization, token, and registration to auth.monday.com.
    authorizationOrigins: ["https://mcp.monday.com", "https://auth.monday.com"],
    scopes: [],
    brand: "monday",
  }),
  remote({
    id: "clickup",
    serverId: "lemmacomputer_clickup",
    serverName: "lemmacomputer_clickup",
    name: "ClickUp",
    shortDescription: "Work with tasks, docs, and workspace work",
    description: "Use the ClickUp tasks, documents, and workspace context your account authorizes.",
    category: "Productivity",
    services: ["Tasks", "Docs", "Workspace search"],
    endpointUrl: "https://mcp.clickup.com/mcp",
    authorizationOrigins: ["https://mcp.clickup.com", "https://app.clickup.com"],
    scopes: [],
    brand: "clickup",
  }),
  remote({
    id: "calendly",
    serverId: "lemmacomputer_calendly",
    serverName: "lemmacomputer_calendly",
    name: "Calendly",
    shortDescription: "Manage scheduling and availability",
    description: "Use the Calendly scheduling links, event types, availability, and meetings your account authorizes.",
    category: "Productivity",
    services: ["Availability", "Event types", "Scheduling"],
    endpointUrl: "https://mcp.calendly.com",
    authorizationOrigins: ["https://calendly.com"],
    scopes: ["mcp:scheduling:read", "mcp:scheduling:write"],
    brand: "calendly",
  }),
  remote({
    id: "fireflies",
    serverId: "lemmacomputer_fireflies",
    serverName: "lemmacomputer_fireflies",
    name: "Fireflies.ai",
    shortDescription: "Search meeting transcripts and action items",
    description: "Use the Fireflies meeting transcripts, summaries, action items, and insights your account authorizes.",
    category: "Productivity",
    services: ["Transcripts", "Summaries", "Action items"],
    endpointUrl: "https://api.fireflies.ai/mcp",
    authorizationOrigins: ["https://api.fireflies.ai"],
    scopes: [],
    brand: "fireflies",
  }),
  remote({
    id: "box",
    withheld: STATIC_CREDENTIALS_REQUIRED,
    serverId: "lemmacomputer_box",
    serverName: "lemmacomputer_box",
    name: "Box",
    shortDescription: "Search, organize, and use Box content",
    description: "Use files, folders, and Box AI features allowed by your Box account.",
    category: "Productivity",
    services: ["Files", "Folders", "Search"],
    endpointUrl: "https://mcp.box.com",
    authorizationOrigins: ["https://mcp.box.com", "https://account.box.com"],
    scopes: [],
    brand: "box",
  }),
  remote({
    id: "exa",
    serverId: "lemmacomputer_exa",
    serverName: "lemmacomputer_exa",
    name: "Exa",
    shortDescription: "Search the web",
    description: "Find current web information and read page content through Exa search.",
    category: "Search",
    services: ["Web search", "Page content", "Research"],
    endpointUrl: "https://mcp.exa.ai/mcp",
    authorizationOrigins: ["https://auth.exa.ai"],
    scopes: ["mcp:tools"],
    brand: "exa",
  }),
  remote({
    id: "github",
    serverId: "lemmacomputer_github",
    serverName: "lemmacomputer_github",
    name: "GitHub",
    shortDescription: "Repositories, issues, and pull requests",
    description: "Work with repositories, issues, and pull requests allowed by your GitHub organization.",
    category: "Developer tools",
    services: ["Repositories", "Issues", "Pull requests"],
    endpointUrl: "https://api.githubcopilot.com/mcp/",
    authorizationOrigins: ["https://github.com"],
    scopes: ["repo", "read:org", "read:user", "user:email"],
    brand: "github",
  }),
  remote({
    id: "vercel",
    withheld: REGISTRATION_ALLOWLISTED,
    serverId: "lemmacomputer_vercel",
    serverName: "lemmacomputer_vercel",
    name: "Vercel",
    shortDescription: "Manage projects, deployments, and logs",
    description: "Use the Vercel projects and deployments your account authorizes.",
    category: "Developer tools",
    services: ["Projects", "Deployments", "Logs"],
    endpointUrl: "https://mcp.vercel.com",
    authorizationOrigins: ["https://mcp.vercel.com", "https://vercel.com"],
    scopes: [],
    brand: "vercel",
  }),
  remote({
    id: "supabase",
    serverId: "lemmacomputer_supabase",
    serverName: "lemmacomputer_supabase",
    name: "Supabase",
    shortDescription: "Work with Supabase projects and data",
    description: "Use the Supabase projects, database, and development tools your account authorizes.",
    category: "Developer tools",
    services: ["Projects", "Database", "Functions"],
    endpointUrl: "https://mcp.supabase.com/mcp",
    // Supabase serves OAuth metadata and all three endpoints from api.supabase.com.
    authorizationOrigins: ["https://mcp.supabase.com", "https://supabase.com", "https://api.supabase.com"],
    scopes: [],
    brand: "supabase",
  }),
  remote({
    id: "neon",
    serverId: "lemmacomputer_neon",
    serverName: "lemmacomputer_neon",
    name: "Neon",
    shortDescription: "Manage Neon projects, branches, and databases",
    description: "Use the Neon projects, branches, databases, and development tools your account authorizes.",
    category: "Developer tools",
    services: ["Projects", "Branches", "Databases"],
    endpointUrl: "https://mcp.neon.tech/mcp",
    authorizationOrigins: ["https://mcp.neon.tech"],
    scopes: [],
    brand: "neon",
  }),
  remote({
    id: "cloudflare-api",
    serverId: "lemmacomputer_cloudflare_api",
    serverName: "lemmacomputer_cloudflare_api",
    name: "Cloudflare",
    shortDescription: "Manage Cloudflare services through approved tools",
    description: "Use the Cloudflare account permissions you grant through its official API MCP server.",
    category: "Developer tools",
    services: ["DNS", "Workers", "Zero Trust"],
    endpointUrl: "https://mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
  remote({
    id: "cloudflare-workers-builds",
    serverId: "lemmacomputer_cloudflare_workers_builds",
    serverName: "lemmacomputer_cloudflare_workers_builds",
    name: "Cloudflare Workers Builds",
    shortDescription: "Inspect and manage Workers builds",
    description: "Use the Cloudflare Workers Builds information your account authorizes.",
    category: "Developer tools",
    services: ["Builds", "Deployments", "Diagnostics"],
    endpointUrl: "https://builds.mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://builds.mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
  remote({
    id: "hubspot",
    withheld: STATIC_CREDENTIALS_REQUIRED,
    serverId: "lemmacomputer_hubspot",
    serverName: "lemmacomputer_hubspot",
    name: "HubSpot",
    shortDescription: "Search CRM records and customer work",
    description: "Use the CRM records and permissions your HubSpot account authorizes.",
    category: "Business",
    services: ["Contacts", "Companies", "Deals"],
    endpointUrl: "https://mcp.hubspot.com",
    authorizationOrigins: ["https://mcp.hubspot.com", "https://app.hubspot.com"],
    scopes: [],
    brand: "hubspot",
  }),
  remote({
    id: "intercom",
    withheld: REGISTRATION_ALLOWLISTED,
    serverId: "lemmacomputer_intercom",
    serverName: "lemmacomputer_intercom",
    name: "Intercom",
    shortDescription: "Use customer conversations and contacts",
    description: "Use Intercom conversations and data available to your authorized account.",
    category: "Business",
    services: ["Conversations", "Contacts", "Help Center"],
    endpointUrl: "https://mcp.intercom.com/mcp",
    authorizationOrigins: ["https://mcp.intercom.com", "https://app.intercom.com"],
    scopes: [],
    brand: "intercom",
  }),
  remote({
    id: "slack",
    withheld: STATIC_CREDENTIALS_REQUIRED,
    serverId: "lemmacomputer_slack",
    serverName: "lemmacomputer_slack",
    name: "Slack",
    shortDescription: "Search channels and work with approved Slack context",
    description: "Use messages, channels, and canvases from a Slack workspace after your organization registers and approves the required Slack MCP app.",
    category: "Communication",
    services: ["Messages", "Channels", "Canvases"],
    endpointUrl: "https://mcp.slack.com/mcp",
    authorizationOrigins: ["https://mcp.slack.com", "https://slack.com"],
    scopes: [],
    brand: "slack",
  }),
  remote({
    id: "alpha-vantage",
    withheld: REGISTRATION_ALLOWLISTED,
    serverId: "lemmacomputer_alpha_vantage",
    serverName: "lemmacomputer_alpha_vantage",
    name: "Alpha Vantage",
    shortDescription: "Research market prices, fundamentals, and macro data",
    description: "Use Alpha Vantage market prices, fundamentals, technical indicators, foreign exchange, crypto, and macroeconomic data.",
    category: "Data and analytics",
    services: ["Prices", "Fundamentals", "Macro data"],
    endpointUrl: "https://mcp.alphavantage.co/mcp",
    authorizationOrigins: ["https://mcp.alphavantage.co"],
    scopes: [],
    brand: "alpha-vantage",
  }),
  remote({
    id: "massive",
    serverId: "lemmacomputer_massive",
    serverName: "lemmacomputer_massive",
    name: "Massive",
    shortDescription: "Research market prices, trades, quotes, and options",
    description: "Use the Massive market prices, trades, quotes, options chains, and historical data your account authorizes.",
    category: "Data and analytics",
    services: ["Prices", "Trades and quotes", "Options"],
    endpointUrl: "https://mcp.massive.com/",
    // Massive delegates its whole OAuth flow to auth.massive.com.
    authorizationOrigins: ["https://mcp.massive.com", "https://massive.com", "https://auth.massive.com"],
    scopes: [],
    brand: "massive",
  }),
  remote({
    id: "intrinio",
    withheld: REGISTRATION_ALLOWLISTED,
    serverId: "lemmacomputer_intrinio",
    serverName: "lemmacomputer_intrinio",
    name: "Intrinio",
    shortDescription: "Research institutional financial data",
    description: "Use the Intrinio prices, fundamentals, estimates, ETFs, options, filings, and events your account authorizes.",
    category: "Data and analytics",
    services: ["Fundamentals", "Estimates", "Market data"],
    endpointUrl: "https://intrinio-mcp.intrinio.com/mcp",
    authorizationOrigins: ["https://intrinio-mcp.intrinio.com", "https://intrinio.com"],
    scopes: [],
    brand: "intrinio",
  }),
  remote({
    id: "cloudflare-observability",
    serverId: "lemmacomputer_cloudflare_observability",
    serverName: "lemmacomputer_cloudflare_observability",
    name: "Cloudflare Observability",
    shortDescription: "Inspect application logs and analytics",
    description: "Use Cloudflare observability data that your account authorizes.",
    category: "Data and analytics",
    services: ["Logs", "Analytics", "Diagnostics"],
    endpointUrl: "https://observability.mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://observability.mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
  remote({
    id: "cloudflare-radar",
    serverId: "lemmacomputer_cloudflare_radar",
    serverName: "lemmacomputer_cloudflare_radar",
    name: "Cloudflare Radar",
    shortDescription: "Explore Internet trends and URL scans",
    description: "Use Cloudflare Radar data and utilities through the official remote MCP server.",
    category: "Data and analytics",
    services: ["Traffic trends", "URL scans", "Internet insights"],
    endpointUrl: "https://radar.mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://radar.mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
  remote({
    id: "cloudflare-graphql",
    serverId: "lemmacomputer_cloudflare_graphql",
    serverName: "lemmacomputer_cloudflare_graphql",
    name: "Cloudflare GraphQL",
    shortDescription: "Query Cloudflare analytics data",
    description: "Use the Cloudflare GraphQL analytics data your account authorizes.",
    category: "Data and analytics",
    services: ["Analytics", "Metrics", "Queries"],
    endpointUrl: "https://graphql.mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://graphql.mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
  remote({
    id: "stripe",
    serverId: "lemmacomputer_stripe",
    serverName: "lemmacomputer_stripe",
    name: "Stripe",
    shortDescription: "Work with payments and billing data",
    description: "Use the Stripe account permissions you grant through Stripe's official MCP server.",
    category: "Business",
    services: ["Payments", "Customers", "Subscriptions"],
    endpointUrl: "https://mcp.stripe.com",
    // Stripe serves OAuth metadata and all three endpoints from access.stripe.com.
    authorizationOrigins: ["https://mcp.stripe.com", "https://dashboard.stripe.com", "https://access.stripe.com"],
    scopes: [],
    brand: "stripe",
  }),
  remote({
    id: "cloudflare-audit-logs",
    serverId: "lemmacomputer_cloudflare_audit_logs",
    serverName: "lemmacomputer_cloudflare_audit_logs",
    name: "Cloudflare Audit Logs",
    shortDescription: "Review Cloudflare audit activity",
    description: "Query the Cloudflare audit logs that your account authorizes.",
    category: "Other",
    services: ["Audit logs", "Reports", "Review"],
    endpointUrl: "https://auditlogs.mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://auditlogs.mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
  remote({
    id: "cloudflare-one-casb",
    serverId: "lemmacomputer_cloudflare_one_casb",
    serverName: "lemmacomputer_cloudflare_one_casb",
    name: "Cloudflare One CASB",
    shortDescription: "Review SaaS security configuration",
    description: "Use Cloudflare One CASB findings that your account authorizes.",
    category: "Other",
    services: ["SaaS posture", "Findings", "Review"],
    endpointUrl: "https://casb.mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://casb.mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
];

export const connectorCatalog = (tenantId: string, microsoftAuthorizationOrigin: string): SaveConnectorRegistryRecord[] => [
  {
    tenantId,
    id: "microsoft-365",
    serverId: "lemmacomputer_ms365",
    serverName: "lemmacomputer_ms365",
    name: "Microsoft 365",
    shortDescription: "Mail, calendar, files, and Teams",
    description: "Use approved Microsoft 365 tools through the LemmaComputer AI gateway. Protected actions require approval.",
    category: "Productivity",
    services: ["Outlook Mail", "Calendar", "OneDrive", "Teams"],
    endpointUrl: "http://ms365-mcp:3000/mcp",
    authorizationOrigins: [new URL(microsoftAuthorizationOrigin).origin],
    scopes: ["User.Read", "offline_access", "Mail.ReadWrite", "Mail.Send", "Calendars.ReadWrite", "Files.ReadWrite", "Chat.Read", "ChatMessage.Read", "ChatMessage.Send", "Team.ReadBasic.All", "Channel.ReadBasic.All", "ChannelMessage.Read.All", "ChannelMessage.Send"],
    policySupport: "governed",
    brand: "microsoft",
    source: "built-in",
    createdBy: "lemmacomputer",
  },
  ...remoteCatalog
    .filter((connector) => !connector.withheld)
    .map(({ withheld: _withheld, ...connector }) => ({ tenantId, ...connector })),
];

// Withheld entries and why, for operator documentation and for the test that
// keeps every withholding reason deliberate rather than incidental.
export const withheldConnectors = (): Array<{ id: string; name: string; reason: string }> =>
  remoteCatalog
    .filter((connector) => connector.withheld)
    .map((connector) => ({ id: connector.id, name: connector.name, reason: connector.withheld! }));
