import type { ConnectorRegistryRecord, SaveConnectorRegistryRecord } from "@onecomputer/workspace-store";

export type ConnectorDefinition = ConnectorRegistryRecord;

export type ConnectorActivationReadiness = "ready" | "setup_required" | "request_access";
export type ConnectorActivationAction = "connect" | "view_setup" | "view_requirements";

export type ConnectorActivation = {
  readiness: ConnectorActivationReadiness;
  action: ConnectorActivationAction;
  message: string;
};

type CatalogConnector = Omit<SaveConnectorRegistryRecord, "tenantId">;

const remote = (connector: Omit<CatalogConnector, "policySupport" | "source" | "createdBy">): CatalogConnector => ({
  ...connector,
  policySupport: "automatic",
  source: "built-in",
  createdBy: "onecomputer",
});

const readyActivation: ConnectorActivation = { readiness: "ready", action: "connect", message: "This approved service is ready to connect." };
const setupRequiredActivation: ConnectorActivation = { readiness: "setup_required", action: "view_setup", message: "This service needs organization setup before people can connect." };
const requestAccessActivation: ConnectorActivation = { readiness: "request_access", action: "view_requirements", message: "This service needs provider approval or organization access before people can connect." };

// An entry is direct-connect only when ONEComputer has an approved provider
// flow. Unknown entries default to request access rather than inviting a
// misleading OAuth attempt.
const builtInActivation: Record<string, ConnectorActivation> = {
  "microsoft-365": readyActivation,
  notion: readyActivation,
  linear: readyActivation,
  atlassian: readyActivation,
  figma: setupRequiredActivation,
  supabase: readyActivation,
  github: setupRequiredActivation,
  vercel: setupRequiredActivation,
  hubspot: setupRequiredActivation,
  slack: setupRequiredActivation,
  asana: requestAccessActivation,
  box: requestAccessActivation,
  intercom: requestAccessActivation,
  stripe: requestAccessActivation,
};

export const connectorActivation = (connector: Pick<ConnectorDefinition, "id" | "source">): ConnectorActivation => {
  if (connector.source === "custom") return { ...readyActivation };
  return { ...(builtInActivation[connector.id] ?? requestAccessActivation) };
};

// These are provider-hosted remote MCP endpoints, not a tool allowlist. The
// Connections screen may display the full catalog without registering every
// server. Control registers one only after its owner selects Connect, and the
// runtime projection still requires that person's successful connection.
const remoteCatalog: CatalogConnector[] = [
  remote({
    id: "notion",
    serverId: "onecomputer_notion",
    serverName: "onecomputer_notion",
    name: "Notion",
    shortDescription: "Search and update workspace knowledge",
    description: "Search and update the pages, databases, and knowledge your Notion account can access.",
    category: "Productivity",
    services: ["Pages", "Databases", "Search"],
    endpointUrl: "https://mcp.notion.com/mcp",
    authorizationOrigins: ["https://mcp.notion.com"],
    scopes: ["default"],
    brand: "notion",
  }),
  remote({
    id: "linear",
    serverId: "onecomputer_linear",
    serverName: "onecomputer_linear",
    name: "Linear",
    shortDescription: "Plan projects, issues, and product work",
    description: "Plan and follow product work across the issues, projects, and comments your account can access.",
    category: "Productivity",
    services: ["Issues", "Projects", "Comments"],
    endpointUrl: "https://mcp.linear.app/mcp",
    authorizationOrigins: ["https://mcp.linear.app"],
    scopes: ["read"],
    brand: "linear",
  }),
  remote({
    id: "atlassian",
    serverId: "onecomputer_atlassian",
    serverName: "onecomputer_atlassian",
    name: "Atlassian",
    shortDescription: "Work across Jira and Confluence",
    description: "Bring approved Jira work and Confluence knowledge into your workspace.",
    category: "Productivity",
    services: ["Jira", "Confluence", "Teamwork Graph"],
    endpointUrl: "https://mcp.atlassian.com/v1/mcp/authv2",
    authorizationOrigins: ["https://auth.atlassian.com"],
    scopes: [
      "read:me",
      "read:account",
      "offline_access",
      "email",
      "read:jira-work",
      "search:confluence",
      "read:confluence-user",
      "read:page:confluence",
      "read:comment:confluence",
      "read:space:confluence",
    ],
    brand: "atlassian",
  }),
  remote({
    id: "asana",
    serverId: "onecomputer_asana",
    serverName: "onecomputer_asana",
    name: "Asana",
    shortDescription: "Manage tasks, projects, and reports",
    description: "Work with the tasks and projects your Asana account is authorized to access.",
    category: "Productivity",
    services: ["Tasks", "Projects", "Reports"],
    endpointUrl: "https://mcp.asana.com/v2/mcp",
    authorizationOrigins: ["https://mcp.asana.com", "https://app.asana.com"],
    scopes: [],
    brand: "asana",
  }),
  remote({
    id: "figma",
    serverId: "onecomputer_figma",
    serverName: "onecomputer_figma",
    name: "Figma",
    shortDescription: "Use design context from Figma files",
    description: "Retrieve the design context, variables, and components your Figma account can access.",
    category: "Productivity",
    services: ["Design context", "Components", "Variables"],
    endpointUrl: "https://mcp.figma.com/mcp",
    authorizationOrigins: ["https://mcp.figma.com", "https://www.figma.com"],
    scopes: [],
    brand: "figma",
  }),
  remote({
    id: "box",
    serverId: "onecomputer_box",
    serverName: "onecomputer_box",
    name: "Box",
    shortDescription: "Search, organize, and use Box content",
    description: "Use files, folders, and Box AI features allowed by your Box account.",
    category: "Productivity",
    services: ["Files", "Folders", "Search"],
    endpointUrl: "https://mcp.box.com",
    authorizationOrigins: ["https://mcp.box.com", "https://account.box.com"],
    scopes: [],
    brand: "box",
  }),
  remote({
    id: "github",
    serverId: "onecomputer_github",
    serverName: "onecomputer_github",
    name: "GitHub",
    shortDescription: "Repositories, issues, and pull requests",
    description: "Work with repositories, issues, and pull requests allowed by your GitHub organization.",
    category: "Developer tools",
    services: ["Repositories", "Issues", "Pull requests"],
    endpointUrl: "https://api.githubcopilot.com/mcp/",
    authorizationOrigins: ["https://github.com"],
    scopes: ["repo", "read:org", "read:user", "user:email"],
    brand: "github",
  }),
  remote({
    id: "vercel",
    serverId: "onecomputer_vercel",
    serverName: "onecomputer_vercel",
    name: "Vercel",
    shortDescription: "Manage projects, deployments, and logs",
    description: "Use the Vercel projects and deployments your account authorizes.",
    category: "Developer tools",
    services: ["Projects", "Deployments", "Logs"],
    endpointUrl: "https://mcp.vercel.com",
    authorizationOrigins: ["https://mcp.vercel.com", "https://vercel.com"],
    scopes: [],
    brand: "vercel",
  }),
  remote({
    id: "supabase",
    serverId: "onecomputer_supabase",
    serverName: "onecomputer_supabase",
    name: "Supabase",
    shortDescription: "Work with Supabase projects and data",
    description: "Use the Supabase projects, database, and development tools your account authorizes.",
    category: "Developer tools",
    services: ["Projects", "Database", "Functions"],
    endpointUrl: "https://mcp.supabase.com/mcp",
    authorizationOrigins: ["https://mcp.supabase.com", "https://supabase.com"],
    scopes: [],
    brand: "supabase",
  }),
  remote({
    id: "cloudflare-api",
    serverId: "onecomputer_cloudflare_api",
    serverName: "onecomputer_cloudflare_api",
    name: "Cloudflare",
    shortDescription: "Manage Cloudflare services through approved tools",
    description: "Use the Cloudflare account permissions you grant through its official API MCP server.",
    category: "Developer tools",
    services: ["DNS", "Workers", "Zero Trust"],
    endpointUrl: "https://mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
  remote({
    id: "cloudflare-workers-builds",
    serverId: "onecomputer_cloudflare_workers_builds",
    serverName: "onecomputer_cloudflare_workers_builds",
    name: "Cloudflare Workers Builds",
    shortDescription: "Inspect and manage Workers builds",
    description: "Use the Cloudflare Workers Builds information your account authorizes.",
    category: "Developer tools",
    services: ["Builds", "Deployments", "Diagnostics"],
    endpointUrl: "https://builds.mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://builds.mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
  remote({
    id: "hubspot",
    serverId: "onecomputer_hubspot",
    serverName: "onecomputer_hubspot",
    name: "HubSpot",
    shortDescription: "Search CRM records and customer work",
    description: "Use the CRM records and permissions your HubSpot account authorizes.",
    category: "Business",
    services: ["Contacts", "Companies", "Deals"],
    endpointUrl: "https://mcp.hubspot.com",
    authorizationOrigins: ["https://mcp.hubspot.com", "https://app.hubspot.com"],
    scopes: [],
    brand: "hubspot",
  }),
  remote({
    id: "intercom",
    serverId: "onecomputer_intercom",
    serverName: "onecomputer_intercom",
    name: "Intercom",
    shortDescription: "Use customer conversations and contacts",
    description: "Use Intercom conversations and data available to your authorized account.",
    category: "Business",
    services: ["Conversations", "Contacts", "Help Center"],
    endpointUrl: "https://mcp.intercom.com/mcp",
    authorizationOrigins: ["https://mcp.intercom.com", "https://app.intercom.com"],
    scopes: [],
    brand: "intercom",
  }),
  remote({
    id: "slack",
    serverId: "onecomputer_slack",
    serverName: "onecomputer_slack",
    name: "Slack",
    shortDescription: "Search channels and work with approved Slack context",
    description: "Use messages, channels, and canvases from a Slack workspace after your organization registers and approves the required Slack MCP app.",
    category: "Communication",
    services: ["Messages", "Channels", "Canvases"],
    endpointUrl: "https://mcp.slack.com/mcp",
    authorizationOrigins: ["https://mcp.slack.com", "https://slack.com"],
    scopes: [],
    brand: "slack",
  }),
  remote({
    id: "cloudflare-observability",
    serverId: "onecomputer_cloudflare_observability",
    serverName: "onecomputer_cloudflare_observability",
    name: "Cloudflare Observability",
    shortDescription: "Inspect application logs and analytics",
    description: "Use Cloudflare observability data that your account authorizes.",
    category: "Data and analytics",
    services: ["Logs", "Analytics", "Diagnostics"],
    endpointUrl: "https://observability.mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://observability.mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
  remote({
    id: "cloudflare-radar",
    serverId: "onecomputer_cloudflare_radar",
    serverName: "onecomputer_cloudflare_radar",
    name: "Cloudflare Radar",
    shortDescription: "Explore Internet trends and URL scans",
    description: "Use Cloudflare Radar data and utilities through the official remote MCP server.",
    category: "Data and analytics",
    services: ["Traffic trends", "URL scans", "Internet insights"],
    endpointUrl: "https://radar.mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://radar.mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
  remote({
    id: "cloudflare-graphql",
    serverId: "onecomputer_cloudflare_graphql",
    serverName: "onecomputer_cloudflare_graphql",
    name: "Cloudflare GraphQL",
    shortDescription: "Query Cloudflare analytics data",
    description: "Use the Cloudflare GraphQL analytics data your account authorizes.",
    category: "Data and analytics",
    services: ["Analytics", "Metrics", "Queries"],
    endpointUrl: "https://graphql.mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://graphql.mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
  remote({
    id: "stripe",
    serverId: "onecomputer_stripe",
    serverName: "onecomputer_stripe",
    name: "Stripe",
    shortDescription: "Work with payments and billing data",
    description: "Use the Stripe account permissions you grant through Stripe's official MCP server.",
    category: "Business",
    services: ["Payments", "Customers", "Subscriptions"],
    endpointUrl: "https://mcp.stripe.com",
    authorizationOrigins: ["https://mcp.stripe.com", "https://dashboard.stripe.com"],
    scopes: [],
    brand: "stripe",
  }),
  remote({
    id: "cloudflare-audit-logs",
    serverId: "onecomputer_cloudflare_audit_logs",
    serverName: "onecomputer_cloudflare_audit_logs",
    name: "Cloudflare Audit Logs",
    shortDescription: "Review Cloudflare audit activity",
    description: "Query the Cloudflare audit logs that your account authorizes.",
    category: "Other",
    services: ["Audit logs", "Reports", "Review"],
    endpointUrl: "https://auditlogs.mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://auditlogs.mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
  remote({
    id: "cloudflare-one-casb",
    serverId: "onecomputer_cloudflare_one_casb",
    serverName: "onecomputer_cloudflare_one_casb",
    name: "Cloudflare One CASB",
    shortDescription: "Review SaaS security configuration",
    description: "Use Cloudflare One CASB findings that your account authorizes.",
    category: "Other",
    services: ["SaaS posture", "Findings", "Review"],
    endpointUrl: "https://casb.mcp.cloudflare.com/mcp",
    authorizationOrigins: ["https://casb.mcp.cloudflare.com", "https://dash.cloudflare.com"],
    scopes: [],
    brand: "cloudflare",
  }),
];

export const connectorCatalog = (tenantId: string, microsoftAuthorizationOrigin: string): SaveConnectorRegistryRecord[] => [
  {
    tenantId,
    id: "microsoft-365",
    serverId: "onecomputer_ms365",
    serverName: "onecomputer_ms365",
    name: "Microsoft 365",
    shortDescription: "Mail, calendar, files, and Teams",
    description: "Use approved Microsoft 365 tools through the ONEComputer AI gateway. Protected actions require approval.",
    category: "Productivity",
    services: ["Outlook Mail", "Calendar", "OneDrive", "Teams"],
    endpointUrl: "http://ms365-mcp:3000/mcp",
    authorizationOrigins: [new URL(microsoftAuthorizationOrigin).origin],
    scopes: ["User.Read", "offline_access", "Mail.ReadWrite", "Mail.Send", "Calendars.ReadWrite", "Files.ReadWrite", "Chat.Read", "ChatMessage.Read", "ChatMessage.Send", "Team.ReadBasic.All", "Channel.ReadBasic.All", "ChannelMessage.Read.All", "ChannelMessage.Send"],
    policySupport: "governed",
    brand: "microsoft",
    source: "built-in",
    createdBy: "onecomputer",
  },
  ...remoteCatalog.map((connector) => ({ tenantId, ...connector })),
];
