import type { ConnectorRegistryRecord, SaveConnectorRegistryRecord } from "@onecomputer/workspace-store";

export type ConnectorDefinition = ConnectorRegistryRecord;

export const connectorCatalog = (tenantId: string, microsoftAuthorizationOrigin: string): SaveConnectorRegistryRecord[] => [
  {
    tenantId,
    id: "microsoft-365",
    serverId: "onecomputer_ms365",
    serverName: "onecomputer_ms365",
    name: "Microsoft 365",
    shortDescription: "Mail, calendar, files, and Teams",
    description: "Use approved Microsoft 365 tools through the ONEComputer AI gateway. Protected actions require approval.",
    category: "Productivity",
    services: ["Outlook Mail", "Calendar", "OneDrive", "Teams"],
    endpointUrl: "http://ms365-mcp:3000/mcp",
    authorizationOrigins: [new URL(microsoftAuthorizationOrigin).origin],
    scopes: ["User.Read", "offline_access", "Mail.ReadWrite", "Mail.Send", "Calendars.ReadWrite", "Files.ReadWrite", "Chat.Read", "ChatMessage.Read", "ChatMessage.Send", "Team.ReadBasic.All", "Channel.ReadBasic.All", "ChannelMessage.Read.All", "ChannelMessage.Send"],
    policySupport: "governed",
    brand: "microsoft",
    source: "built-in",
    createdBy: "onecomputer",
  },
  {
    tenantId,
    id: "notion",
    serverId: "onecomputer_notion",
    serverName: "onecomputer_notion",
    name: "Notion",
    shortDescription: "Search and update workspace knowledge",
    description: "Search and update the pages, databases, and knowledge your Notion account can access.",
    category: "Productivity",
    services: ["Pages", "Databases", "Search"],
    endpointUrl: "https://mcp.notion.com/mcp",
    authorizationOrigins: ["https://mcp.notion.com"],
    scopes: ["default"],
    policySupport: "automatic",
    brand: "notion",
    source: "built-in",
    createdBy: "onecomputer",
  },
  {
    tenantId,
    id: "linear",
    serverId: "onecomputer_linear",
    serverName: "onecomputer_linear",
    name: "Linear",
    shortDescription: "Plan projects, issues, and product work",
    description: "Plan and follow product work across the issues, projects, and comments your account can access.",
    category: "Productivity",
    services: ["Issues", "Projects", "Comments"],
    endpointUrl: "https://mcp.linear.app/mcp",
    authorizationOrigins: ["https://mcp.linear.app"],
    scopes: ["read"],
    policySupport: "automatic",
    brand: "linear",
    source: "built-in",
    createdBy: "onecomputer",
  },
  {
    tenantId,
    id: "atlassian",
    serverId: "onecomputer_atlassian",
    serverName: "onecomputer_atlassian",
    name: "Atlassian",
    shortDescription: "Work across Jira and Confluence",
    description: "Bring approved Jira work and Confluence knowledge into your workspace.",
    category: "Productivity",
    services: ["Jira", "Confluence", "Teamwork Graph"],
    endpointUrl: "https://mcp.atlassian.com/v1/mcp/authv2",
    authorizationOrigins: ["https://auth.atlassian.com"],
    scopes: [
      "read:me",
      "read:account",
      "offline_access",
      "email",
      "read:jira-work",
      "search:confluence",
      "read:confluence-user",
      "read:page:confluence",
      "read:comment:confluence",
      "read:space:confluence",
    ],
    policySupport: "automatic",
    brand: "atlassian",
    source: "built-in",
    createdBy: "onecomputer",
  },
  {
    tenantId,
    id: "github",
    serverId: "onecomputer_github",
    serverName: "onecomputer_github",
    name: "GitHub",
    shortDescription: "Repositories, issues, and pull requests",
    description: "Work with repositories, issues, and pull requests allowed by your GitHub organization.",
    category: "Developer tools",
    services: ["Repositories", "Issues", "Pull requests"],
    endpointUrl: "https://api.githubcopilot.com/mcp/",
    authorizationOrigins: ["https://github.com"],
    scopes: ["repo", "read:org", "read:user", "user:email"],
    policySupport: "automatic",
    brand: "github",
    source: "built-in",
    createdBy: "onecomputer",
  },
];
