import assert from "node:assert/strict";import test from "node:test";
import {RoutingAdministrationService,changeRoutingRolloutSchema,saveRoutingPolicySchema} from "../apps/control-api/src/routing.js";
import type {RoutingStore} from "@onecomputer/workspace-store";
const uuid={team:"11111111-1111-4111-8111-111111111111",mapping:"22222222-2222-4222-8222-222222222222",policy:"33333333-3333-4333-8333-333333333333",deployment:"44444444-4444-4444-8444-444444444444",review:"55555555-5555-4555-8555-555555555555"};
const identity={allowedServiceClasses:["lite","balanced","pro"] as const,allowedDeploymentIds:[uuid.deployment],explicitSelectionAllowed:true,forceServiceClass:null,safeDefault:"balanced" as const};
const classContract={capabilityFloor:{vision:false,tools:false,streaming:true,contextTokens:8000,outputTokens:1000},evaluationThreshold:"0.800000",qualityPosture:"standard",costPosture:"balanced",latencyPosture:"balanced",requiredModalities:["text"],requiredResidency:["sg"],eligibleDeploymentIds:[uuid.deployment],safeDefault:false};const serviceClassPolicies={lite:classContract,balanced:{...classContract,safeDefault:true},pro:classContract};
test("Team routing schema can narrow but never widen identity policy",()=>{const base={mappingVersionId:uuid.mapping,billingCurrency:"USD",serviceClassPolicies,identity};assert.ok(saveRoutingPolicySchema.safeParse({...base,team:{...identity,allowedServiceClasses:["lite"]}}).success);assert.equal(saveRoutingPolicySchema.safeParse({...base,identity:{...identity,allowedServiceClasses:["lite"]},team:{...identity,allowedServiceClasses:["lite","pro"]}}).success,false)});
test("production enablement requires both evidence and an explicit typed confirmation",()=>{const base={policyVersionId:uuid.policy,mappingVersionId:uuid.mapping,mode:"enabled",fixedDeploymentId:uuid.deployment,evidenceReviewId:uuid.review,reason:"Representative evidence passed review"};assert.equal(changeRoutingRolloutSchema.safeParse(base).success,false);assert.ok(changeRoutingRolloutSchema.safeParse({...base,confirmation:"ENABLE AUTO ROUTING"}).success);assert.equal(changeRoutingRolloutSchema.safeParse({...base,evidenceReviewId:undefined,confirmation:"ENABLE AUTO ROUTING"}).success,false)});
test("administration service always projects the authenticated tenant into store calls",async()=>{const calls:string[]=[];const store={adminReadModel:async(tenantId:string)=>{calls.push(tenantId);return{teamId:uuid.team,policy:null,rollout:null,review:null,deployments:[]}},shadowReport:async(tenantId:string)=>{calls.push(tenantId);return{}},decision:async(tenantId:string)=>{calls.push(tenantId);return null}} as unknown as RoutingStore;const service=new RoutingAdministrationService(store);await service.settings({tenantId:"tenant-a",userId:"admin"},uuid.team);await service.report({tenantId:"tenant-a",userId:"admin"},uuid.team);await service.decision({tenantId:"tenant-a",userId:"admin"},uuid.policy);assert.deepEqual(calls,["tenant-a","tenant-a","tenant-a"])});
