import { existsSync, readFileSync } from "node:fs";
import { rename, unlink, writeFile } from "node:fs/promises";
import {
  environmentContract,
  firstPartyImageVariables,
  resolveDeploymentEnvironment,
  serializeEnvironment,
} from "./deployment-config.mjs";

export function parseEnvironment(contents) {
  const entries = [];
  for (const [index, line] of contents.split(/\r?\n/).entries()) {
    const match = line.match(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/);
    if (match) entries.push({ key: match[1], value: match[2], line: index + 1 });
  }
  const values = new Map();
  const counts = new Map();
  for (const entry of entries) {
    values.set(entry.key, entry.value);
    counts.set(entry.key, (counts.get(entry.key) ?? 0) + 1);
  }
  return {
    entries,
    values,
    duplicates: [...counts.entries()]
      .filter(([, count]) => count > 1)
      .map(([key]) => key),
  };
}


// These values describe an installation's identity, not operator choices.
// Preserve them across updates and include them in installation backups.
const managedNames = new Set([
  ...environmentContract.filter((item) => item.generated).map((item) => item.key),
  ...firstPartyImageVariables,
  "LEMMACOMPUTER_APP_VERSION",
  "LEMMACOMPUTER_COMPOSE_PROJECT_NAME",
  "LEMMACOMPUTER_CONTROL_NETWORK",
  "LEMMACOMPUTER_CONTROL_CONTAINER",
  "LEMMACOMPUTER_LITELLM_CONTAINER",
  "LEMMACOMPUTER_WORKSPACE_NODE_ID",
  "LEMMACOMPUTER_KASM_LOCAL_NETWORK_PREFIX",
  "LEMMACOMPUTER_KASM_LOCAL_EGRESS_NETWORK",
]);

const visibleNames = new Set([
  "LEMMACOMPUTER_INSTALLATION_KIND",
  "LEMMACOMPUTER_RUNTIME_ENVIRONMENT",
  "LEMMACOMPUTER_PUBLIC_WEB_URL",
  "LEMMACOMPUTER_WEB_PORT",
  "LEMMACOMPUTER_TIME_ZONE",
]);

function readValues(path, optional = false) {
  let contents;
  try { contents = readFileSync(path, "utf8"); } catch (error) {
    if (optional && error.code === "ENOENT") return {};
    throw error;
  }
  const parsed = parseEnvironment(contents);
  if (parsed.duplicates.length) throw new Error(`Duplicate variables in ${path}: ${parsed.duplicates.join(", ")}`);
  return Object.fromEntries(parsed.values);
}

/** Also accepts existing, single-file installations without modifying them. */
export function readEnvironmentFiles(source = ".env", { resolved = false } = {}) {
  if (!existsSync(`${source}.state`) && readFileSync(source, "utf8").startsWith("# Installation settings.")) {
    throw new Error(`${source}.state is missing; restore installation state from backup, do not regenerate its keys`);
  }
  const managed = readValues(`${source}.state`, true);
  const operator = readValues(source);
  for (const key of Object.keys(operator)) {
    if (Object.hasOwn(managed, key) && managed[key] !== operator[key]) {
      throw new Error(`${key} has conflicting values in ${source} and ${source}.state; keep it in one file`);
    }
  }
  const values = { ...managed, ...operator };
  return resolved ? { ...values, ...resolveDeploymentEnvironment(values) } : values;
}

export function partitionEnvironment(input) {
  const values = input instanceof Map ? Object.fromEntries(input) : input;
  const operator = {};
  const managed = {};
  const known = new Set(environmentContract.map((item) => item.key));
  for (const item of environmentContract) {
    if (!Object.hasOwn(values, item.key)) continue;
    const value = values[item.key];
    if (managedNames.has(item.key)) managed[item.key] = value;
    else if (visibleNames.has(item.key) || value !== item.default) operator[item.key] = value;
  }
  // Unrecognized values may belong to operator tooling. Never discard them.
  for (const [key, value] of Object.entries(values)) {
    if (!known.has(key)) managed[key] = value;
  }
  const operatorLines = [
    "# Installation settings. Never commit this file.",
    "# Defaults and optional settings: .env.example.",
    "# Generated keys and deployment identity: the adjacent .state file. Back up both.",
  ];
  let lastSection;
  for (const item of environmentContract) {
    if (!Object.hasOwn(operator, item.key)) continue;
    if (item.section !== lastSection) {
      operatorLines.push("", `# ${item.section}`);
      lastSection = item.section;
    }
    operatorLines.push(`# ${item.description}`, `${item.key}=${operator[item.key]}`);
  }
  return {
    operator: `${operatorLines.join("\n")}\n`,
    managed: "# Persistent installation state. Generated by setup; never commit or regenerate.\n"
      + "# Contains keys, image references, resource identity, and preserved legacy values.\n"
      + "# Back up with .env and the installation data. Not a disposable runtime projection.\n"
      + serializeEnvironment(managed),
  };
}

async function atomicWrite(path, contents) {
  const temporary = `${path}.update-${process.pid}`;
  try {
    await writeFile(temporary, contents, { mode: 0o600, flag: "wx" });
    await rename(temporary, path);
  } finally {
    await unlink(temporary).catch((error) => { if (error.code !== "ENOENT") throw error; });
  }
}

export async function writeEnvironmentFiles(source, values) {
  const files = partitionEnvironment(values);
  // State first: interruption leaves identical duplicate values in an old
  // full .env, which the reader accepts without losing or rotating secrets.
  await atomicWrite(`${source}.state`, files.managed);
  await atomicWrite(source, files.operator);
}
