import { createHash } from "node:crypto";
import { access, chmod, readFile, rm, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";

const run = (command, args, options = {}) => {
  const result = spawnSync(command, args, { encoding: "utf8", ...options });
  if (result.status !== 0) throw new Error(result.stderr || `${command} failed`);
  return result.stdout.trim();
};
const exists = (path) => access(path).then(() => true).catch(() => false);
const root = run("git", ["rev-parse", "--show-toplevel"]);
process.chdir(root);
const branch = run("git", ["branch", "--show-current"]);
if (!branch || branch === "main") throw new Error("Worktree bootstrap is forbidden on main; create an issue branch/worktree first");
const id = createHash("sha256").update(`${root}\0${branch}`).digest("hex").slice(0, 10);
const slug = `oc-${id}`;
const portOffset = 1000 + (Number.parseInt(id.slice(0, 6), 16) % 20000);

const localModules = resolve(root, "node_modules");
if (!await exists(localModules)) {
  const install = spawnSync("npm", ["ci"], { stdio: "inherit" });
  if (install.status !== 0) throw new Error("npm ci failed");
}

if (!await exists(".env")) run(process.execPath, ["scripts/initialize-env.mjs"]);
const envPath = resolve(root, ".env");
const current = await readFile(envPath, "utf8");
const overrides = new Map([
  ["ONECOMPUTER_COMPOSE_PROJECT_NAME", slug],
  ["ONECOMPUTER_CONTROL_NETWORK", `${slug}-control`],
  ["ONECOMPUTER_CONTROL_CONTAINER", `${slug}-control-api`],
  ["ONECOMPUTER_LITELLM_CONTAINER", `${slug}-litellm`],
  ["ONECOMPUTER_IMAGE_TAG", `dev-${id}`],
  ["ONECOMPUTER_MS365_IMAGE_TAG", `dev-${id}`],
  ["ONECOMPUTER_WORKSPACE_IMAGE", `onecomputer/workspace:dev-${id}`],
  ["KASM_LOCAL_NETWORK_PREFIX", `${slug}-workspace`],
  ["KASM_LOCAL_EGRESS_NETWORK", `${slug}-egress`],
  ["ONECOMPUTER_WEB_PORT", String(4174 + portOffset)],
  ["ONECOMPUTER_LITELLM_PORT", String(4000 + portOffset)],
  ["ONECOMPUTER_M365_PORT", String(4311 + portOffset)],
  ["ONECOMPUTER_PUBLIC_WEB_URL", `http://localhost:${4174 + portOffset}`],
  ["ONECOMPUTER_LITELLM_PUBLIC_URL", `http://localhost:${4000 + portOffset}`],
  ["ONECOMPUTER_M365_AUTHORIZATION_ORIGIN", `http://localhost:${4311 + portOffset}`],
  ["ONECOMPUTER_INSTALLATION_KIND", "worktree"],
]);
const seen = new Set();
const lines = current.trimEnd().split(/\r?\n/).map((line) => {
  const match = line.match(/^([A-Z][A-Z0-9_]*)=/);
  if (!match || !overrides.has(match[1])) return line;
  seen.add(match[1]);
  return `${match[1]}=${overrides.get(match[1])}`;
});
const missingOverrides = [...overrides].filter(([key]) => !seen.has(key));
if (missingOverrides.length) {
  lines.push("", "# Worktree isolation (generated by npm run worktree:init)");
  for (const [key, value] of missingOverrides) lines.push(`${key}=${value}`);
}
await writeFile(envPath, `${lines.join("\n")}\n`, { mode: 0o600 });

for (const mountedFile of [
  "config/litellm/config.yaml",
  "config/litellm/logging.yaml",
  "integrations/litellm/onecomputer_policy_callback.py",
]) await chmod(mountedFile, 0o644);
await rm(".artifacts/release-verification", { recursive: true, force: true });
process.stdout.write([
  `Worktree ${branch} is isolated as ${slug}.`,
  `Web: http://localhost:${4174 + portOffset}`,
  "Fresh worktree secrets are in .env; provider and Entra placeholders still need local values for full sign-in tests.",
  "Run npm run dev:doctor before starting work.",
  "",
].join("\n"));
